repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.2
    hooks:
      # Linter.
      - id: ruff
        args: ["--select=I", "--fix", "--show-fixes"]
      # Formatter.
      - id: ruff-format

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        exclude: guacamole_handler/templates/
